name: deploy to github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Packages
        run: npm install

      - name: Generate Metadata
        run: npm run gen-meta
        env:
          ONLY_FIRST: "false"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build package
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: app
          path: ./www

      - name: Publish to blob storage
        uses: bacongobbler/azure-blob-storage-upload@v1.0.0
        with:
          source_dir: ./www
          container_name: $web
          connection_string: ${{ secrets.ConnectionString }}
          extra_args: ""
