name: pr-ci

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          
      - name: Install Packages
        run: npm install
        
      - name: Build package
        run: npm run build
